/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#c5ecc9",
        "on-tertiary-container": "#40403d",
        "surface-bright": "#f9f9f7",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#aad0ae",
        "primary-container": "#c9a84c",
        "inverse-primary": "#e6c364",
        "surface-container-low": "#f4f4f2",
        "tertiary-fixed": "#e5e2de",
        "outline-variant": "#d0c5b2",
        "surface-dim": "#dadad8",
        "on-secondary-fixed-variant": "#2c4e34",
        "secondary-fixed": "#c5ecc9",
        "surface-container-highest": "#e2e3e1",
        "secondary": "#44664b",
        "primary-fixed-dim": "#e6c364",
        "tertiary-container": "#adaba8",
        "on-background": "#1a1c1b",
        "surface-container": "#eeeeec",
        "on-surface": "#1a1c1b",
        "on-secondary-fixed": "#00210c",
        "surface-container-high": "#e8e8e6",
        "on-secondary-container": "#4a6c50",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#241a00",
        "on-secondary": "#ffffff",
        "on-primary-container": "#503d00",
        "surface": "#f9f9f7",
        "tertiary": "#5f5e5c",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1c1c1a",
        "inverse-surface": "#2f3130",
        "surface-tint": "#755b00",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#584400",
        "primary-fixed": "#ffe08f",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f1ef",
        "surface-variant": "#e2e3e1",
        "primary": "#755b00",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#474744",
        "tertiary-fixed-dim": "#c8c6c3",
        "background": "#FAFAF8",
        "on-primary": "#ffffff",
        "on-surface-variant": "#4d4637",
        "outline": "#7e7665"
      },
      fontFamily: {
        "headline": ["Be Vietnam Pro"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
    },
  },
  plugins: [],
}
